# SPDX-FileCopyrightText: Copyright 2024 Siemens AG
# SPDX-License-Identifier: MIT

repos:
  - repo: local
    hooks:
      - id: commitizen
        name: Commitizen check
        entry: cz
        args: ['check', '--commit-msg-file', '.git/COMMIT_EDITMSG']
        pass_filenames: false
        language: system
        stages: [commit-msg]

      - id: ruff-format
        name: Ruff – Format code
        entry: ruff format --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true

      - id: ruff-lint
        name: Ruff – Lint
        entry: ruff check --force-exclude --fix
        language: system
        types_or: [python, pyi]
        require_serial: true

      - id: poetry-check
        name: Poetry – Check `pyproject.toml`
        entry: poetry check
        language: system
        pass_filenames: false
        files: ^pyproject.toml$

      - id: poetry-check-lock
        name: Poetry – Check `poetry.lock`
        entry: poetry lock --check
        language: system
        pass_filenames: false
        files: ^pyproject.toml|poetry.lock$

      # - id: renovate-config-validator
      #   name: Renovate – Check configuration
      #   entry: renovate-config-validator --strict
      #   language: node
      #   additional_dependencies: [renovate@37.269.3]
      #   files: (^|/).?renovate(?:rc)?(?:\.json5?)?$

      - id: trailing-whitespace
        name: Trim trailing whitespace
        entry: trailing-whitespace-fixer
        language: system
        types: [text]
        stages: [commit, push, manual]

      - id: end-of-file-fixer
        name: Fix end of files
        entry: end-of-file-fixer
        language: system
        types: [text]
        stages: [commit, push, manual]

      - id: check-merge-conflict
        name: Check for merge conflicts
        entry: check-merge-conflict
        args: [--assume-in-merge]
        language: system
        types: [text]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
