site_name: Python Test
site_description: Python Test
site_author: dibog@github.com

repo_url: https://github.com/dibog/python_Test.git
edit_uri: edit/master/docs/

copyright: "Copyright &copy; 2024 Dibog"

nav:
  - 'Home': index.md

theme:
  name: material
  palette:
    primary: teal
    accent: teal
  language: en
  features:
    - navigation.instant

extra:
  page_license_text: MIT
  community:
    community_button_headline: Any questions left?
    community_button_text: Create an issue
    community_button_default_href: issues
  links:
    - name: code
      value: readme.md
    - name: issues
      value: readme.md

markdown_extensions:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      guess_lang: true
  - pymdownx.snippets:
      base_path: ./docs
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tasklist
