# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python pull request workflow

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install poetry
      run: pipx install poetry

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'poetry'

    - run: poetry install

    - name: Check pre-commit
      run: poetry run pre-commit run -a

    - name: Build Wheel
      run: poetry build

    - name: Build pages
      run: poetry run mkdocs build -s -d _site
