# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'poetry'

      - run: poetry install
      - run: poetry run pre-commit run -a
      - run: poetry build
      - run: cz changelog
      - run: env | sort

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            CHANGELOG.md
            LICENSE
            dist/*
